---
- name: search for an ami image
  ec2_ami_search: >
    region={{ region|default('us-east-1') }}
    store={{ store|default('ebs') }}
    virt={{ virt|default('hvm') }}
    distro={{ distro|default('redhat') }}
    release={{ release|default('precise') }}
  register: ami_data
#x86_64-redhat-linux-gnu
- name: debug ami image
  debug: 'msg="{{ ami_data }}"'

- name: start the ec2 instance
  local_action:
    module: ec2
    key_name: "{{ keypair|default('mykey') }}"
    group: "{{ securitygroup|default('mygroup') }}"
    instance_type: "{{ instancetype|default('t2.micro')}}"
    image: "{{ ami_data.ami }}"
    region: "{{ region|default('us-west-2b') }}"
    wait: no
    instance_tags:
        Name: "{{ name|default('myinstance')}}"
        foo: bar
  register: instance_data

- name: debug instance start
  debug: 'msg="{{instance_data }}"'
